# Manipuler des tableaux
Dans cette feuille, vous allez apprendre à effectuer quelques manipulations simples sur les tableaux. En Python, de tels tableaux peuvent être représentés les `array` de la bibliothèque `numpy` (usuellement abrégée en `np`):

In [1]:
import numpy as np

Voilà un tableau avec deux lignes et quatre colomnes:

In [2]:
T = np.array([[ 1, 2, 3, 4],[ 5, 6, 7, 8]])

In [3]:
T

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

On peut retrouver les tailles de ce tableau avec:

In [4]:
T.shape

(2, 4)

## Exercice
1. Construire un tableau à trois lignes et trois colonnes, avec les entiers de 1 à 9 de gauche à droite et de haut en bas

In [5]:
### BEGIN SOLUTION
T2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
### END SOLUTION

2. Vérifiez ses dimensions

In [6]:
T2.shape

(3, 3)

Voici comment accéder au contenu d'une case individuelle du tableau:

In [7]:
T[1,2]

7

Cette case et en deuxième ligne et troisième colonne: en effet, les lignes et colones sont numérotées à partir de 0.

Si l'on veut extraire toute une ligne, ou toute une colonne, on remplace la coordonée que l'on ne veut pas spécifier par `:`. Voici donc la deuxième colonne:

In [8]:
T[:,1]

array([2, 6])

Pour le moment, nous avons utilisé des tableaux à deux dimensions.
Pour représenter une image, ce ne sera pas suffisant: il ne suffit pas d'un nombre pour représenter un pixel.
Numpy permet de représenter des tableaux de toute dimension. Voici un tableau de dimension 3:

In [9]:
T3D = np.array(  [[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[10,11,12],
                   [13,14,15],
                   [16,17,18]],
                  [[19,20,21],
                   [22,23,24],
                   [25,26,27]]])                

On peut le voir comme un tableau à trois couches:

In [10]:
T3D[0,:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
T3D[1,:,:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
T3D[2,:,:]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

## Exercice
Extraire un tableau contenant les trois premières colonnes des trois couches de `T`?

In [13]:
### BEGIN SOLUTION
T3D[:,:,0]
### END SOLUTION

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

# Statistiques sur les tableaux


Numpy permet de faire des statistiques simples sur les tableaux. Calculer à la main la moyenne de tous les éléments du tableaux, la moyenne de chaque ligne et la moyenne de chaque colonne. Comparer avec les résultats des calculs suivants:

In [14]:
T.mean()

4.5

In [15]:
T.mean(axis=0)

array([3., 4., 5., 6.])

In [16]:
T.mean(axis=1)

array([2.5, 6.5])

Vous pouvez maintenant revenir à la [feuille sur les images](images.ipynb)